CREATE DATABASE IF NOT EXISTS mahasiswa_sammialdhiyanto;
SHOW DATABASES;
USE mahasiswa_sammialdhiyanto;

CREATE TABLE ALUMNI_SammiAldhiYanto (
    NIM VARCHAR(8) DEFAULT NULL,
    TMPT_LAHIR VARCHAR(100) DEFAULT NULL ,
    TGL_LAHIR DATE DEFAULT NULL ,
    PRODI ENUM('SI','TI') DEFAULT NULL,
    EMAIL VARCHAR(100) DEFAULT NULL,
    IPK TEXT DEFAULT NULL ,
    KELAMIN ENUM('PRIA','WANITA') DEFAULT NULL,
    THN_MASUK INT DEFAULT NULL,
    THN_LULU INT DEFAULT NULL,
    JUDUL VARCHAR(100) DEFAULT NULL
);

ALTER TABLE alumni_sammialdhiyanto
    DROP COLUMN JUDUL;

ALTER TABLE alumni_sammialdhiyanto
    ADD COLUMN id INT PRIMARY KEY AUTO_INCREMENT FIRST;

SELECT AVG(IPK) FROM ALUMNI_SammiAldhiYanto;
SELECT AVG(IPK) FROM ALUMNI_SammiAldhiYanto WHERE KELAMIN = 'PRIA';
SELECT AVG(IPK) FROM ALUMNI_SammiAldhiYanto WHERE KELAMIN = 'WANITA';
SELECT AVG(IPK) FROM ALUMNI_SammiAldhiYanto WHERE PRODI = 'SI';
SELECT AVG(IPK) FROM ALUMNI_SammiAldhiYanto WHERE PRODI = 'TI';
SELECT MIN(IPK) FROM ALUMNI_SammiAldhiYanto WHERE PRODI = 'TI' AND KELAMIN = 'PRIA';
SELECT MIN(IPK) FROM ALUMNI_SammiAldhiYanto where PRODI = 'SI' AND KELAMIN = 'WANITA';
SELECT COUNT(id) AS 'Total Alumni Prodi TI' FROM alumni_sammialdhiyanto;
SELECT COUNT(id) AS 'Total Alumni Prodi SI Kelahiran Pekanbaru' FROM alumni_sammialdhiyanto WHERE PRODI = 'SI' AND TMPT_LAHIR = 'Pekanbaru';
SELECT COUNT(id) AS 'Total alumni yg memiliki ipk diatas 3,50' FROM alumni_sammialdhiyanto WHERE IPK > '3,50';